variables:
    REPO_NAME: "reverse-registry"
    DOCKER_TLS_CERTDIR: "/certs" # sharing same certificate between docker client and daemon

stages:
    - build

build_image:
    stage: build
    image: docker:20.10.16
    services:
        - docker:20.10.16-dind # docker in docker (docker daemon)
    before_script:
        - echo "$AWS_REGION"
        - apk add --no-cache curl jq python3 py3-pip
        - pip install awscli
        - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
        - aws --version
        - docker --version
    script:
        - docker build -t $REPO_NAME/frontend:1.0 -f ./frontend/Dockerfile ./frontend
        - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME/frontend:1.0
        # - docker build -t $REPO_NAME/auth-backend:1.0 -f ./backend/auth/AuthDockerfile ./backend/auth
        # - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME/auth-backend:1.0
        # - docker build -t $REPO_NAME/archive-backend:1.0 -f ./backend/archive/ArchiveDockerfile ./backend/archive
        # - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME/archive-backend:1.0
        # - docker build -t $REPO_NAME/signal-backend:1.0 -f ./signal/SignalDockerfile ./signal
        # - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME/signal-backend:1.0
    tags:
        - reverse-runner
