server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://reverse-archive.clpjhqrsb3pu.ap-northeast-2.rds.amazonaws.com:3306/reverse_archive?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: flQjtm1024
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 50MB
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
        use_sql_comments: true
  redis:
    host: reverse-redis.akqgni.ng.0001.apn2.cache.amazonaws.com
    port: 6379

logging:
  level:
    root: info
    org.springframework.web: error
    org.springframework.boot: debug
    org.apache.tiles: info
    kr.co.reverse.archive: debug


cloud:
  aws:
    credentials:
      access-key: AKIA35FT7NQ63VIMM2LP
      secret-key: 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
    s3:
      bucket: re-verse-bucket
    #        url: https://s3.ap-northeast-2.amazonaws.com/re-verse-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

#elasticsearch:
#  endpoint: search-reverse-elastic-search-wwjxyhiofuvlhmriehomivboqe.ap-northeast-2.es.amazonaws.com
#  region: ap-northeast-2
#  port: 9200
#  protocol: https
#  username: reverse
#  password: flQjtm1024$

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK